### PR TITLE
fix decimal problem on slider

### PR DESCRIPTION
**Pull request by khusmann**
hello, I've put this together as a quick fix for the decimal problem on the regular slider as well. thx!

### CODE REVIEW

**Comment by khusmann** [comment]
Relevant issue: #16

**Comment by khusmann** [comment]
oops, I didn't do it quite right -- when I let go of the slider it rounds it down to the nearest int... gotta run now, can look closer at it later...

**Comment by khusmann** [comment]
oh, actually, the incorrect rounding was in the code I was using to test... this pull request is actually good, I think!

**Comment by avishain** [comment]
Done along with other changes I made.
Thanks for your time.

**Pull request closed without merging**
